export const menuItems = [
  {
    id: 1,
    name: "Grilled Salmon",
    price: 24.99,
    category: "Main Course",
    available: true,
    demandScore: 85,
    image:
      "https://images.unsplash.com/photo-1485921325833-c519f76c4927?auto=format&fit=crop&q=80&w=400",
    description:
      "Fresh Atlantic salmon grilled to perfection, served with seasonal vegetables",
  },
  {
    id: 2,
    name: "Tiramisu",
    price: 8.99,
    category: "Desserts",
    available: true,
    demandScore: 92,
    image:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&q=80&w=400",
    description:
      "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream",
  },
  {
    id: 3,
    name: "Caprese Salad",
    price: 12.99,
    category: "Starters",
    available: true,
    demandScore: 78,
    image:
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?auto=format&fit=crop&q=80&w=400",
    description:
      "Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze",
  },
  {
    id: 4,
    name: "Wagyu Beef Burger",
    price: 28.99,
    category: "Main Course",
    available: true,
    demandScore: 95,
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=400",
    description:
      "Premium Wagyu beef patty with truffle aioli, caramelized onions, and aged cheddar",
  },
  {
    id: 5,
    name: "Lobster Risotto",
    price: 34.99,
    category: "Main Course",
    available: true,
    demandScore: 88,
    image:
      "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=400",
    description:
      "Creamy Arborio rice with fresh lobster, finished with aged Parmesan",
  },
  {
    id: 6,
    name: "Chocolate Lava Cake",
    price: 10.99,
    category: "Desserts",
    available: true,
    demandScore: 90,
    image:
      "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=400",
    description:
      "Warm chocolate cake with a molten center, served with vanilla ice cream",
  },
  {
    id: 7,
    name: "Truffle Fries",
    price: 9.99,
    category: "Sides",
    available: true,
    demandScore: 82,
    image:
      "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=400",
    description:
      "Crispy fries tossed with truffle oil, Parmesan, and fresh herbs",
  },
  {
    id: 8,
    name: "Tuna Tartare",
    price: 18.99,
    category: "Starters",
    available: true,
    demandScore: 86,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400",
    description: "Fresh tuna with avocado, sesame oil, and won ton crisps",
  },
];

export const categories = [
  "All",
  "Main Course",
  "Starters",
  "Desserts",
  "Sides",
];

export const salesData = [
  { time: "8:00", sales: 1200 },
  { time: "10:00", sales: 2100 },
  { time: "12:00", sales: 3200 },
  { time: "14:00", sales: 2800 },
  { time: "16:00", sales: 1900 },
  { time: "18:00", sales: 2400 },
  { time: "20:00", sales: 3100 },
];

export const mockOrders = [
  {
    id: "1",
    customer: "John Doe",
    items: [
      { menuItemId: 1, name: "Grilled Salmon", quantity: 1, price: 24.99 },
    ],
    total: 24.99,
    status: "completed",
    createdAt: new Date().toISOString(),
  },
];

export const toPredict = [
  {
    id: 1,
    name: "Grilled Salmon",
    prev_day_sales: 85,
    last_weekday_sales: 100,
    prev_month_sales: 120,
    last_year_sales: 150,
    profit: 20,
    category: "Main Course", // Added category
  },
  {
    id: 2,
    name: "Tiramisu",
    prev_day_sales: 92,
    last_weekday_sales: 110,
    prev_month_sales: 130,
    last_year_sales: 160,
    profit: 15,
    category: "Desserts", // Added category
  },
  {
    id: 3,
    name: "Caprese Salad",
    prev_day_sales: 78,
    last_weekday_sales: 90,
    prev_month_sales: 95,
    last_year_sales: 125,
    profit: 10,
    category: "Starters", // Added category
  },
  {
    id: 4,
    name: "Wagyu Beef Burger",
    prev_day_sales: 95,
    last_weekday_sales: 110,
    prev_month_sales: 140,
    last_year_sales: 200,
    profit: 25,
    category: "Main Course", // Added category
  },
  {
    id: 5,
    name: "Lobster Risotto",
    prev_day_sales: 88,
    last_weekday_sales: 105,
    prev_month_sales: 125,
    last_year_sales: 175,
    profit: 22,
    category: "Main Course", // Added category
  },
  {
    id: 6,
    name: "Chocolate Lava Cake",
    prev_day_sales: 90,
    last_weekday_sales: 100,
    prev_month_sales: 110,
    last_year_sales: 130,
    profit: 12,
    category: "Desserts", // Added category
  },
  {
    id: 7,
    name: "Truffle Fries",
    prev_day_sales: 82,
    last_weekday_sales: 95,
    prev_month_sales: 100,
    last_year_sales: 120,
    profit: 8,
    category: "Sides", // Added category
  },
  {
    id: 8,
    name: "Tuna Tartare",
    prev_day_sales: 86,
    last_weekday_sales: 90,
    prev_month_sales: 115,
    last_year_sales: 140,
    profit: 18,
    category: "Starters", // Added category
  },
];

// export const procurementCategories = {
//   vegetables: [
//     {
//       id: 1,
//       name: "Tomatoes",
//       quantity: 10,
//       unit: "kg",
//       status: "normal",
//       trend: "up",
//     },
//     {
//       id: 2,
//       name: "Onions",
//       quantity: 15,
//       unit: "kg",
//       status: "low",
//       trend: "down",
//     },
//     {
//       id: 3,
//       name: "Lettuce",
//       quantity: 20,
//       unit: "heads",
//       status: "normal",
//       trend: "stable",
//     },
//     {
//       id: 4,
//       name: "Bell Peppers",
//       quantity: 5,
//       unit: "kg",
//       status: "critical",
//       trend: "down",
//     },
//   ],
//   meat: [
//     {
//       id: 5,
//       name: "Chicken Breast",
//       quantity: 25,
//       unit: "kg",
//       status: "normal",
//       trend: "up",
//     },
//     {
//       id: 6,
//       name: "Ground Beef",
//       quantity: 15,
//       unit: "kg",
//       status: "low",
//       trend: "stable",
//     },
//     {
//       id: 7,
//       name: "Pork Chops",
//       quantity: 10,
//       unit: "kg",
//       status: "normal",
//       trend: "down",
//     },
//   ],
//   dairy: [
//     {
//       id: 8,
//       name: "Milk",
//       quantity: 30,
//       unit: "L",
//       status: "normal",
//       trend: "stable",
//     },
//     {
//       id: 9,
//       name: "Cheese",
//       quantity: 8,
//       unit: "kg",
//       status: "low",
//       trend: "down",
//     },
//     {
//       id: 10,
//       name: "Butter",
//       quantity: 5,
//       unit: "kg",
//       status: "critical",
//       trend: "down",
//     },
//   ],
//   spices: [
//     {
//       id: 11,
//       name: "Black Pepper",
//       quantity: 2,
//       unit: "kg",
//       status: "normal",
//       trend: "stable",
//     },
//     {
//       id: 12,
//       name: "Salt",
//       quantity: 5,
//       unit: "kg",
//       status: "normal",
//       trend: "up",
//     },
//     {
//       id: 13,
//       name: "Cumin",
//       quantity: 1,
//       unit: "kg",
//       status: "low",
//       trend: "down",
//     },
//   ],
// };
export const procurementCategories = {
  vegetables: [
    {
      id: 1,
      name: "Tomatoes",
      currentStock: 10,
      unit: "kg",
      minRequired: 15,
      recommendedOrder: 10,
      averageDaily: 8,
      lastOrdered: "2 days ago",
      price: 2.5,
      status: "low",
    },
    {
      id: 2,
      name: "Onions",
      currentStock: 20,
      unit: "kg",
      minRequired: 25,
      recommendedOrder: 15,
      averageDaily: 10,
      lastOrdered: "3 days ago",
      price: 1.8,
      status: "normal",
    },
  ],
  meat: [
    {
      id: 3,
      name: "Chicken Breast",
      currentStock: 5,
      unit: "kg",
      minRequired: 20,
      recommendedOrder: 25,
      averageDaily: 15,
      lastOrdered: "1 day ago",
      price: 8.5,
      status: "critical",
    },
  ],
  dairy: [
    {
      id: 4,
      name: "Cheese",
      currentStock: 8,
      unit: "kg",
      minRequired: 10,
      recommendedOrder: 5,
      averageDaily: 3,
      lastOrdered: "4 days ago",
      price: 12,
      status: "low",
    },
  ],
  spices: [
    {
      id: 5,
      name: "Black Pepper",
      currentStock: 2,
      unit: "kg",
      minRequired: 3,
      recommendedOrder: 2,
      averageDaily: 0.5,
      lastOrdered: "7 days ago",
      price: 15,
      status: "normal",
    },
  ],
};

export const timeSlots = [
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
];

// export const scheduleData = {
//   "8:00": [
//     {
//       id: 1,
//       task: "Prep vegetables",
//       assignee: "John",
//       duration: 60,
//       type: "prep",
//     },
//     {
//       id: 2,
//       task: "Make sauces",
//       assignee: "Maria",
//       duration: 45,
//       type: "prep",
//     },
//   ],
//   "9:00": [
//     {
//       id: 3,
//       task: "Prepare lunch specials",
//       assignee: "Mike",
//       duration: 120,
//       type: "cooking",
//     },
//   ],
//   "10:00": [
//     {
//       id: 4,
//       task: "Inventory check",
//       assignee: "Sarah",
//       duration: 30,
//       type: "admin",
//     },
//   ],
//   "11:00": [
//     {
//       id: 5,
//       task: "Lunch service prep",
//       assignee: "Team",
//       duration: 60,
//       type: "service",
//     },
//   ],
//   "12:00": [
//     {
//       id: 6,
//       task: "Lunch service",
//       assignee: "All staff",
//       duration: 180,
//       type: "service",
//     },
//   ],
//   "15:00": [
//     {
//       id: 7,
//       task: "Clean and reset",
//       assignee: "Team",
//       duration: 60,
//       type: "cleaning",
//     },
//   ],
//   "16:00": [
//     {
//       id: 8,
//       task: "Dinner prep",
//       assignee: "Evening team",
//       duration: 120,
//       type: "prep",
//     },
//   ],
//   "18:00": [
//     {
//       id: 9,
//       task: "Dinner service",
//       assignee: "All staff",
//       duration: 240,
//       type: "service",
//     },
//   ],
// };

export const scheduleData = {
  "08:00": [
    {
      item: "Tomato Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 45,
      priority: "high",
    },
    {
      item: "Chopped Vegetables",
      quantity: 10,
      unit: "kg",
      estimatedTime: 30,
      priority: "medium",
    },
    {
      item: "Bread Dough",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 60,
      priority: "high",
    },
    {
      item: "Grated Cheese",
      quantity: 5,
      unit: "kg",
      estimatedTime: 15,
      priority: "medium",
    },
    {
      item: "Fresh Herbs",
      quantity: 2,
      unit: "kg",
      estimatedTime: 10,
      priority: "low",
    },
    {
      item: "Salad Dressing",
      quantity: 3,
      unit: "L",
      estimatedTime: 20,
      priority: "medium",
    },
    {
      item: "Garlic Paste",
      quantity: 4,
      unit: "kg",
      estimatedTime: 25,
      priority: "medium",
    },
    {
      item: "Spice Mix",
      quantity: 2,
      unit: "kg",
      estimatedTime: 10,
      priority: "low",
    },
    {
      item: "Stock Base",
      quantity: 10,
      unit: "L",
      estimatedTime: 40,
      priority: "high",
    },
    {
      item: "Marinade",
      quantity: 5,
      unit: "L",
      estimatedTime: 30,
      priority: "high",
    },
  ],
  "09:00": [
    {
      item: "Marinated Chicken",
      quantity: 15,
      unit: "kg",
      estimatedTime: 60,
      priority: "high",
    },
    {
      item: "Pizza Dough",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Grilled Veggies",
      quantity: 8,
      unit: "kg",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Soup Base",
      quantity: 12,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Sliced Cold Cuts",
      quantity: 7,
      unit: "kg",
      estimatedTime: 30,
      priority: "medium",
    },
    {
      item: "Steak Marinade",
      quantity: 5,
      unit: "L",
      estimatedTime: 25,
      priority: "high",
    },
    {
      item: "Sauces",
      quantity: 8,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Burger Patties",
      quantity: 30,
      unit: "pieces",
      estimatedTime: 45,
      priority: "high",
    },
    {
      item: "Fish Fillet Prep",
      quantity: 12,
      unit: "kg",
      estimatedTime: 40,
      priority: "medium",
    },
    {
      item: "Mayo Blend",
      quantity: 3,
      unit: "L",
      estimatedTime: 20,
      priority: "low",
    },
  ],
  "10:00": [
    {
      item: "Pasta",
      quantity: 8,
      unit: "kg",
      estimatedTime: 30,
      priority: "medium",
    },
    {
      item: "Soup Stock",
      quantity: 20,
      unit: "L",
      estimatedTime: 120,
      priority: "low",
    },
    {
      item: "Grilled Chicken",
      quantity: 10,
      unit: "kg",
      estimatedTime: 50,
      priority: "high",
    },
    {
      item: "Sautéed Mushrooms",
      quantity: 6,
      unit: "kg",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "French Fries",
      quantity: 15,
      unit: "kg",
      estimatedTime: 40,
      priority: "high",
    },
    {
      item: "Rice Pilaf",
      quantity: 10,
      unit: "kg",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Cream Sauce",
      quantity: 7,
      unit: "L",
      estimatedTime: 25,
      priority: "medium",
    },
    {
      item: "Bread Crumbs",
      quantity: 5,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Tartar Sauce",
      quantity: 4,
      unit: "L",
      estimatedTime: 15,
      priority: "low",
    },
    {
      item: "Sushi Rice",
      quantity: 12,
      unit: "kg",
      estimatedTime: 50,
      priority: "high",
    },
  ],
  "11:00": [
    {
      item: "Lamb Stew",
      quantity: 8,
      unit: "kg",
      estimatedTime: 120,
      priority: "high",
    },
    {
      item: "Roasted Potatoes",
      quantity: 15,
      unit: "kg",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Seafood Marinade",
      quantity: 5,
      unit: "L",
      estimatedTime: 30,
      priority: "medium",
    },
    {
      item: "Herb Butter",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Stuffed Peppers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 50,
      priority: "medium",
    },
    {
      item: "Meatballs",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 60,
      priority: "high",
    },
    {
      item: "Pickled Vegetables",
      quantity: 10,
      unit: "kg",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Fruit Salad",
      quantity: 10,
      unit: "kg",
      estimatedTime: 30,
      priority: "low",
    },
    {
      item: "Pasta Dough",
      quantity: 12,
      unit: "kg",
      estimatedTime: 40,
      priority: "medium",
    },
    {
      item: "Chocolate Ganache",
      quantity: 6,
      unit: "L",
      estimatedTime: 35,
      priority: "low",
    },
  ],
  "12:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "13:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "14:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "15:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "16:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "17:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "16:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "17:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "18:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "19:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "20:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "21:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
  "22:00": [
    {
      item: "Sourdough Bread",
      quantity: 15,
      unit: "loaves",
      estimatedTime: 180,
      priority: "high",
    },
    {
      item: "Beef Stroganoff",
      quantity: 8,
      unit: "kg",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Vegan Burgers",
      quantity: 10,
      unit: "pieces",
      estimatedTime: 45,
      priority: "medium",
    },
    {
      item: "Tomato Soup",
      quantity: 10,
      unit: "L",
      estimatedTime: 60,
      priority: "medium",
    },
    {
      item: "Chicken Broth",
      quantity: 15,
      unit: "L",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Cheesecake Base",
      quantity: 5,
      unit: "kg",
      estimatedTime: 50,
      priority: "low",
    },
    {
      item: "Avocado Mash",
      quantity: 3,
      unit: "kg",
      estimatedTime: 20,
      priority: "low",
    },
    {
      item: "Caramel Sauce",
      quantity: 5,
      unit: "L",
      estimatedTime: 35,
      priority: "medium",
    },
    {
      item: "Gourmet Pizza Base",
      quantity: 20,
      unit: "pieces",
      estimatedTime: 90,
      priority: "high",
    },
    {
      item: "Macaron Prep",
      quantity: 50,
      unit: "pieces",
      estimatedTime: 60,
      priority: "medium",
    },
  ],
};
